.TH "example Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexample_DGELS_colmajor\&.c\fP"
.br
.ti -1c
.RI "file \fBexample_DGELS_rowmajor\&.c\fP"
.br
.ti -1c
.RI "file \fBexample_DGESV_colmajor\&.c\fP"
.br
.ti -1c
.RI "file \fBexample_DGESV_rowmajor\&.c\fP"
.br
.ti -1c
.RI "file \fBexample_user\&.c\fP"
.br
.ti -1c
.RI "file \fBlapacke_example_aux\&.c\fP"
.br
.ti -1c
.RI "file \fBlapacke_example_aux\&.h\fP"
.br
.in -1c
