.TH "LL Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LL Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVARIANTS/qr/LL/cgeqrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/qr/LL/dgeqrf\&.f\fP"
.br
.ti -1c
.RI "file \fBsceil\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/qr/LL/sgeqrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/qr/LL/zgeqrf\&.f\fP"
.br
.in -1c
