.TH "REC Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REC Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVARIANTS/lu/REC/cgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/REC/dgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/REC/sgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/REC/zgetrf\&.f\fP"
.br
.in -1c
