.TH "TOP Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOP Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVARIANTS/cholesky/TOP/cpotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/TOP/dpotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/TOP/spotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/TOP/zpotrf\&.f\fP"
.br
.in -1c
