.TH "RL Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RL Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVARIANTS/cholesky/RL/cpotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/RL/dpotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/RL/spotrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/cholesky/RL/zpotrf\&.f\fP"
.br
.in -1c
