.TH "CR Directory Reference" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CR Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVARIANTS/lu/CR/cgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/CR/dgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/CR/sgetrf\&.f\fP"
.br
.ti -1c
.RI "file \fBVARIANTS/lu/CR/zgetrf\&.f\fP"
.br
.in -1c
