.TH "ccopy.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccopy.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBccopy\fP (\fBN\fP, CX, INCX, CY, INCY)"
.br
.RI "\fBCCOPY\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ccopy (integer N, complex, dimension(*) CX, integer INCX, complex, dimension(*) CY, integer INCY)"

.PP
\fBCCOPY\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
    CCOPY copies a vector x to a vector y.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
         number of elements in input vector(s)
.fi
.PP
.br
\fICX\fP 
.PP
.nf
          CX is COMPLEX array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
         storage spacing between elements of CX
.fi
.PP
.br
\fICY\fP 
.PP
.nf
          CY is COMPLEX array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
         storage spacing between elements of CY
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2017 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, linpack, 3/11/78.
     modified 12/3/93, array(1) declarations changed to array(*)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 83 of file ccopy\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
