.TH "clacgv.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clacgv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBclacgv\fP (\fBN\fP, X, INCX)"
.br
.RI "\fBCLACGV\fP conjugates a complex vector\&. "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine clacgv (integer N, complex, dimension( * ) X, integer INCX)"

.PP
\fBCLACGV\fP conjugates a complex vector\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 CLACGV conjugates a complex vector of length N.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The length of the vector X.  N >= 0.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is COMPLEX array, dimension
                         (1+(N-1)*abs(INCX))
          On entry, the vector of length N to be conjugated.
          On exit, X is overwritten with conjg(X).
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The spacing between successive elements of X.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
December 2016 
.RE
.PP

.PP
Definition at line 76 of file clacgv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
