.TH "dcabs1.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcabs1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "double precision function \fBdcabs1\fP (Z)"
.br
.RI "\fBDCABS1\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "double precision function dcabs1 (complex*16 Z)"

.PP
\fBDCABS1\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 DCABS1 computes |Re(.)| + |Im(.)| of a double complex number
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIZ\fP 
.PP
.nf
          Z is COMPLEX*16
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2017 
.RE
.PP

.PP
Definition at line 49 of file dcabs1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
