.TH "lapacke_stgsja_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_stgsja_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_stgsja_work\fP (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_int\fP l, float *a, \fBlapack_int\fP lda, float *b, \fBlapack_int\fP ldb, float tola, float tolb, float *alpha, float *beta, float *u, \fBlapack_int\fP ldu, float *v, \fBlapack_int\fP ldv, float *q, \fBlapack_int\fP ldq, float *work, \fBlapack_int\fP *ncycle)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_stgsja_work (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_int\fP l, float * a, \fBlapack_int\fP lda, float * b, \fBlapack_int\fP ldb, float tola, float tolb, float * alpha, float * beta, float * u, \fBlapack_int\fP ldu, float * v, \fBlapack_int\fP ldv, float * q, \fBlapack_int\fP ldq, float * work, \fBlapack_int\fP * ncycle)"

.PP
Definition at line 36 of file lapacke_stgsja_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
