.TH "lapacke_cpbstf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cpbstf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cpbstf\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kb, \fBlapack_complex_float\fP *bb, \fBlapack_int\fP ldbb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cpbstf (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kb, \fBlapack_complex_float\fP * bb, \fBlapack_int\fP ldbb)"

.PP
Definition at line 36 of file lapacke_cpbstf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
