.TH "lapacke_cgecon_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgecon_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgecon_work\fP (int matrix_layout, char norm, \fBlapack_int\fP n, const \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, float anorm, float *rcond, \fBlapack_complex_float\fP *work, float *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgecon_work (int matrix_layout, char norm, \fBlapack_int\fP n, const \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, float anorm, float * rcond, \fBlapack_complex_float\fP * work, float * rwork)"

.PP
Definition at line 36 of file lapacke_cgecon_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
