.TH "lapacke_dorbdb.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dorbdb.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dorbdb\fP (int matrix_layout, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, double *x11, \fBlapack_int\fP ldx11, double *x12, \fBlapack_int\fP ldx12, double *x21, \fBlapack_int\fP ldx21, double *x22, \fBlapack_int\fP ldx22, double *theta, double *phi, double *taup1, double *taup2, double *tauq1, double *tauq2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dorbdb (int matrix_layout, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, double * x11, \fBlapack_int\fP ldx11, double * x12, \fBlapack_int\fP ldx12, double * x21, \fBlapack_int\fP ldx21, double * x22, \fBlapack_int\fP ldx22, double * theta, double * phi, double * taup1, double * taup2, double * tauq1, double * tauq2)"

.PP
Definition at line 36 of file lapacke_dorbdb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
