.TH "lapacke_stgsyl.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_stgsyl.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_stgsyl\fP (int matrix_layout, char trans, \fBlapack_int\fP ijob, \fBlapack_int\fP m, \fBlapack_int\fP n, const float *a, \fBlapack_int\fP lda, const float *b, \fBlapack_int\fP ldb, float *c, \fBlapack_int\fP ldc, const float *d, \fBlapack_int\fP ldd, const float *e, \fBlapack_int\fP lde, float *f, \fBlapack_int\fP ldf, float *scale, float *dif)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_stgsyl (int matrix_layout, char trans, \fBlapack_int\fP ijob, \fBlapack_int\fP m, \fBlapack_int\fP n, const float * a, \fBlapack_int\fP lda, const float * b, \fBlapack_int\fP ldb, float * c, \fBlapack_int\fP ldc, const float * d, \fBlapack_int\fP ldd, const float * e, \fBlapack_int\fP lde, float * f, \fBlapack_int\fP ldf, float * scale, float * dif)"

.PP
Definition at line 36 of file lapacke_stgsyl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
