.TH "lapacke_ctrsen.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_ctrsen.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_ctrsen\fP (int matrix_layout, char job, char compq, const \fBlapack_logical\fP *select, \fBlapack_int\fP n, \fBlapack_complex_float\fP *t, \fBlapack_int\fP ldt, \fBlapack_complex_float\fP *q, \fBlapack_int\fP ldq, \fBlapack_complex_float\fP *w, \fBlapack_int\fP *m, float *s, float *sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_ctrsen (int matrix_layout, char job, char compq, const \fBlapack_logical\fP * select, \fBlapack_int\fP n, \fBlapack_complex_float\fP * t, \fBlapack_int\fP ldt, \fBlapack_complex_float\fP * q, \fBlapack_int\fP ldq, \fBlapack_complex_float\fP * w, \fBlapack_int\fP * m, float * s, float * sep)"

.PP
Definition at line 36 of file lapacke_ctrsen\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
