.TH "lapacke_dtrsyl.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dtrsyl.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dtrsyl\fP (int matrix_layout, char trana, char tranb, \fBlapack_int\fP isgn, \fBlapack_int\fP m, \fBlapack_int\fP n, const double *a, \fBlapack_int\fP lda, const double *b, \fBlapack_int\fP ldb, double *c, \fBlapack_int\fP ldc, double *scale)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dtrsyl (int matrix_layout, char trana, char tranb, \fBlapack_int\fP isgn, \fBlapack_int\fP m, \fBlapack_int\fP n, const double * a, \fBlapack_int\fP lda, const double * b, \fBlapack_int\fP ldb, double * c, \fBlapack_int\fP ldc, double * scale)"

.PP
Definition at line 36 of file lapacke_dtrsyl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
