.TH "lapacke_zlaghe_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zlaghe_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zlaghe_work\fP (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP k, const double *d, \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda, \fBlapack_int\fP *iseed, \fBlapack_complex_double\fP *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zlaghe_work (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP k, const double * d, \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda, \fBlapack_int\fP * iseed, \fBlapack_complex_double\fP * work)"

.PP
Definition at line 36 of file lapacke_zlaghe_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
