.TH "lapacke_ztf_nancheck.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_ztf_nancheck.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_logical\fP \fBLAPACKE_ztf_nancheck\fP (int matrix_layout, char transr, char uplo, char diag, \fBlapack_int\fP n, const \fBlapack_complex_double\fP *a)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_logical\fP LAPACKE_ztf_nancheck (int matrix_layout, char transr, char uplo, char diag, \fBlapack_int\fP n, const \fBlapack_complex_double\fP * a)"

.PP
Definition at line 37 of file lapacke_ztf_nancheck\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
