.TH "lapacke_dggbal.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dggbal.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dggbal\fP (int matrix_layout, char job, \fBlapack_int\fP n, double *a, \fBlapack_int\fP lda, double *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *ilo, \fBlapack_int\fP *ihi, double *lscale, double *rscale)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dggbal (int matrix_layout, char job, \fBlapack_int\fP n, double * a, \fBlapack_int\fP lda, double * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * ilo, \fBlapack_int\fP * ihi, double * lscale, double * rscale)"

.PP
Definition at line 36 of file lapacke_dggbal\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
