.TH "lapacke_sppcon.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sppcon.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sppcon\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, const float *ap, float anorm, float *rcond)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sppcon (int matrix_layout, char uplo, \fBlapack_int\fP n, const float * ap, float anorm, float * rcond)"

.PP
Definition at line 36 of file lapacke_sppcon\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
