.TH "lapacke_zheevd_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zheevd_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zheevd_work\fP (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda, double *w, \fBlapack_complex_double\fP *work, \fBlapack_int\fP lwork, double *rwork, \fBlapack_int\fP lrwork, \fBlapack_int\fP *iwork, \fBlapack_int\fP liwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zheevd_work (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda, double * w, \fBlapack_complex_double\fP * work, \fBlapack_int\fP lwork, double * rwork, \fBlapack_int\fP lrwork, \fBlapack_int\fP * iwork, \fBlapack_int\fP liwork)"

.PP
Definition at line 36 of file lapacke_zheevd_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
