.TH "lapacke_zherfs.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zherfs.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zherfs\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda, const \fBlapack_complex_double\fP *af, \fBlapack_int\fP ldaf, const \fBlapack_int\fP *ipiv, const \fBlapack_complex_double\fP *b, \fBlapack_int\fP ldb, \fBlapack_complex_double\fP *x, \fBlapack_int\fP ldx, double *ferr, double *berr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zherfs (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda, const \fBlapack_complex_double\fP * af, \fBlapack_int\fP ldaf, const \fBlapack_int\fP * ipiv, const \fBlapack_complex_double\fP * b, \fBlapack_int\fP ldb, \fBlapack_complex_double\fP * x, \fBlapack_int\fP ldx, double * ferr, double * berr)"

.PP
Definition at line 36 of file lapacke_zherfs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
