.TH "lapacke_zptrfs_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zptrfs_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zptrfs_work\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const double *d, const \fBlapack_complex_double\fP *e, const double *df, const \fBlapack_complex_double\fP *ef, const \fBlapack_complex_double\fP *b, \fBlapack_int\fP ldb, \fBlapack_complex_double\fP *x, \fBlapack_int\fP ldx, double *ferr, double *berr, \fBlapack_complex_double\fP *work, double *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zptrfs_work (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const double * d, const \fBlapack_complex_double\fP * e, const double * df, const \fBlapack_complex_double\fP * ef, const \fBlapack_complex_double\fP * b, \fBlapack_int\fP ldb, \fBlapack_complex_double\fP * x, \fBlapack_int\fP ldx, double * ferr, double * berr, \fBlapack_complex_double\fP * work, double * rwork)"

.PP
Definition at line 36 of file lapacke_zptrfs_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
