.TH "lapacke_chb_nancheck.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_chb_nancheck.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_logical\fP \fBLAPACKE_chb_nancheck\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, const \fBlapack_complex_float\fP *ab, \fBlapack_int\fP ldab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_logical\fP LAPACKE_chb_nancheck (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, const \fBlapack_complex_float\fP * ab, \fBlapack_int\fP ldab)"

.PP
Definition at line 37 of file lapacke_chb_nancheck\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
