.TH "lapacke_cgtsvx_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgtsvx_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgtsvx_work\fP (int matrix_layout, char fact, char trans, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP *dl, const \fBlapack_complex_float\fP *d, const \fBlapack_complex_float\fP *du, \fBlapack_complex_float\fP *dlf, \fBlapack_complex_float\fP *df, \fBlapack_complex_float\fP *duf, \fBlapack_complex_float\fP *du2, \fBlapack_int\fP *ipiv, const \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP *x, \fBlapack_int\fP ldx, float *rcond, float *ferr, float *berr, \fBlapack_complex_float\fP *work, float *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgtsvx_work (int matrix_layout, char fact, char trans, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP * dl, const \fBlapack_complex_float\fP * d, const \fBlapack_complex_float\fP * du, \fBlapack_complex_float\fP * dlf, \fBlapack_complex_float\fP * df, \fBlapack_complex_float\fP * duf, \fBlapack_complex_float\fP * du2, \fBlapack_int\fP * ipiv, const \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP * x, \fBlapack_int\fP ldx, float * rcond, float * ferr, float * berr, \fBlapack_complex_float\fP * work, float * rwork)"

.PP
Definition at line 36 of file lapacke_cgtsvx_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
