.TH "lapacke_zlassq.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zlassq.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zlassq\fP (\fBlapack_int\fP n, \fBlapack_complex_double\fP *x, \fBlapack_int\fP incx, double *scale, double *sumsq)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zlassq (\fBlapack_int\fP n, \fBlapack_complex_double\fP * x, \fBlapack_int\fP incx, double * scale, double * sumsq)"

.PP
Definition at line 36 of file lapacke_zlassq\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
