.TH "lapacke_sptcon.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sptcon.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sptcon\fP (\fBlapack_int\fP n, const float *d, const float *e, float anorm, float *rcond)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sptcon (\fBlapack_int\fP n, const float * d, const float * e, float anorm, float * rcond)"

.PP
Definition at line 36 of file lapacke_sptcon\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
