.TH "lapacke_dgbrfsx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dgbrfsx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dgbrfsx\fP (int matrix_layout, char trans, char equed, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, const double *ab, \fBlapack_int\fP ldab, const double *afb, \fBlapack_int\fP ldafb, const \fBlapack_int\fP *ipiv, const double *r, const double *c, const double *b, \fBlapack_int\fP ldb, double *x, \fBlapack_int\fP ldx, double *rcond, double *berr, \fBlapack_int\fP n_err_bnds, double *err_bnds_norm, double *err_bnds_comp, \fBlapack_int\fP nparams, double *params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dgbrfsx (int matrix_layout, char trans, char equed, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, const double * ab, \fBlapack_int\fP ldab, const double * afb, \fBlapack_int\fP ldafb, const \fBlapack_int\fP * ipiv, const double * r, const double * c, const double * b, \fBlapack_int\fP ldb, double * x, \fBlapack_int\fP ldx, double * rcond, double * berr, \fBlapack_int\fP n_err_bnds, double * err_bnds_norm, double * err_bnds_comp, \fBlapack_int\fP nparams, double * params)"

.PP
Definition at line 36 of file lapacke_dgbrfsx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
