.TH "lapacke_sbdsqr_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sbdsqr_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sbdsqr_work\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ncvt, \fBlapack_int\fP nru, \fBlapack_int\fP ncc, float *d, float *e, float *vt, \fBlapack_int\fP ldvt, float *u, \fBlapack_int\fP ldu, float *c, \fBlapack_int\fP ldc, float *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sbdsqr_work (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ncvt, \fBlapack_int\fP nru, \fBlapack_int\fP ncc, float * d, float * e, float * vt, \fBlapack_int\fP ldvt, float * u, \fBlapack_int\fP ldu, float * c, \fBlapack_int\fP ldc, float * work)"

.PP
Definition at line 36 of file lapacke_sbdsqr_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
