.TH "lapacke_dspgst.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dspgst.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dspgst\fP (int matrix_layout, \fBlapack_int\fP itype, char uplo, \fBlapack_int\fP n, double *ap, const double *bp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dspgst (int matrix_layout, \fBlapack_int\fP itype, char uplo, \fBlapack_int\fP n, double * ap, const double * bp)"

.PP
Definition at line 36 of file lapacke_dspgst\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
