.TH "lapacke_sgeevx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sgeevx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sgeevx\fP (int matrix_layout, char balanc, char jobvl, char jobvr, char sense, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *wr, float *wi, float *vl, \fBlapack_int\fP ldvl, float *vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP *ilo, \fBlapack_int\fP *ihi, float *scale, float *abnrm, float *rconde, float *rcondv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sgeevx (int matrix_layout, char balanc, char jobvl, char jobvr, char sense, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * wr, float * wi, float * vl, \fBlapack_int\fP ldvl, float * vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP * ilo, \fBlapack_int\fP * ihi, float * scale, float * abnrm, float * rconde, float * rcondv)"

.PP
Definition at line 36 of file lapacke_sgeevx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
