.TH "lapacke_strexc.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_strexc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_strexc\fP (int matrix_layout, char compq, \fBlapack_int\fP n, float *t, \fBlapack_int\fP ldt, float *q, \fBlapack_int\fP ldq, \fBlapack_int\fP *ifst, \fBlapack_int\fP *ilst)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_strexc (int matrix_layout, char compq, \fBlapack_int\fP n, float * t, \fBlapack_int\fP ldt, float * q, \fBlapack_int\fP ldq, \fBlapack_int\fP * ifst, \fBlapack_int\fP * ilst)"

.PP
Definition at line 36 of file lapacke_strexc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
