.TH "lapacke_dgtcon_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dgtcon_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dgtcon_work\fP (char norm, \fBlapack_int\fP n, const double *dl, const double *d, const double *du, const double *du2, const \fBlapack_int\fP *ipiv, double anorm, double *rcond, double *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dgtcon_work (char norm, \fBlapack_int\fP n, const double * dl, const double * d, const double * du, const double * du2, const \fBlapack_int\fP * ipiv, double anorm, double * rcond, double * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_dgtcon_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
