.TH "lapacke_zggsvd3.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zggsvd3.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zggsvd3\fP (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP p, \fBlapack_int\fP *k, \fBlapack_int\fP *l, \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda, \fBlapack_complex_double\fP *b, \fBlapack_int\fP ldb, double *alpha, double *beta, \fBlapack_complex_double\fP *u, \fBlapack_int\fP ldu, \fBlapack_complex_double\fP *v, \fBlapack_int\fP ldv, \fBlapack_complex_double\fP *q, \fBlapack_int\fP ldq, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zggsvd3 (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP p, \fBlapack_int\fP * k, \fBlapack_int\fP * l, \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda, \fBlapack_complex_double\fP * b, \fBlapack_int\fP ldb, double * alpha, double * beta, \fBlapack_complex_double\fP * u, \fBlapack_int\fP ldu, \fBlapack_complex_double\fP * v, \fBlapack_int\fP ldv, \fBlapack_complex_double\fP * q, \fBlapack_int\fP ldq, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_zggsvd3\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
