.TH "lapacke_zsteqr_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zsteqr_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zsteqr_work\fP (int matrix_layout, char compz, \fBlapack_int\fP n, double *d, double *e, \fBlapack_complex_double\fP *z, \fBlapack_int\fP ldz, double *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zsteqr_work (int matrix_layout, char compz, \fBlapack_int\fP n, double * d, double * e, \fBlapack_complex_double\fP * z, \fBlapack_int\fP ldz, double * work)"

.PP
Definition at line 36 of file lapacke_zsteqr_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
