.TH "lapacke_sstegr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sstegr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sstegr\fP (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, float *d, float *e, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, float abstol, \fBlapack_int\fP *m, float *w, float *z, \fBlapack_int\fP ldz, \fBlapack_int\fP *isuppz)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sstegr (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, float * d, float * e, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, float abstol, \fBlapack_int\fP * m, float * w, float * z, \fBlapack_int\fP ldz, \fBlapack_int\fP * isuppz)"

.PP
Definition at line 36 of file lapacke_sstegr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
