.TH "lapacke_dgemqrt.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dgemqrt.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dgemqrt\fP (int matrix_layout, char side, char trans, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_int\fP nb, const double *v, \fBlapack_int\fP ldv, const double *t, \fBlapack_int\fP ldt, double *c, \fBlapack_int\fP ldc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dgemqrt (int matrix_layout, char side, char trans, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_int\fP nb, const double * v, \fBlapack_int\fP ldv, const double * t, \fBlapack_int\fP ldt, double * c, \fBlapack_int\fP ldc)"

.PP
Definition at line 36 of file lapacke_dgemqrt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
