.TH "lapacke_chfrk.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_chfrk.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_chfrk\fP (int matrix_layout, char transr, char uplo, char trans, \fBlapack_int\fP n, \fBlapack_int\fP k, float alpha, const \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, float beta, \fBlapack_complex_float\fP *c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_chfrk (int matrix_layout, char transr, char uplo, char trans, \fBlapack_int\fP n, \fBlapack_int\fP k, float alpha, const \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, float beta, \fBlapack_complex_float\fP * c)"

.PP
Definition at line 36 of file lapacke_chfrk\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
