.TH "lapacke_dlarft_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dlarft_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dlarft_work\fP (int matrix_layout, char direct, char storev, \fBlapack_int\fP n, \fBlapack_int\fP k, const double *v, \fBlapack_int\fP ldv, const double *tau, double *t, \fBlapack_int\fP ldt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dlarft_work (int matrix_layout, char direct, char storev, \fBlapack_int\fP n, \fBlapack_int\fP k, const double * v, \fBlapack_int\fP ldv, const double * tau, double * t, \fBlapack_int\fP ldt)"

.PP
Definition at line 36 of file lapacke_dlarft_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
