.TH "lapacke_zlantr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zlantr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBLAPACKE_zlantr\fP (int matrix_layout, char norm, char uplo, char diag, \fBlapack_int\fP m, \fBlapack_int\fP n, const \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double LAPACKE_zlantr (int matrix_layout, char norm, char uplo, char diag, \fBlapack_int\fP m, \fBlapack_int\fP n, const \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda)"

.PP
Definition at line 36 of file lapacke_zlantr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
