.TH "lapacke_sgeev.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sgeev.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sgeev\fP (int matrix_layout, char jobvl, char jobvr, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *wr, float *wi, float *vl, \fBlapack_int\fP ldvl, float *vr, \fBlapack_int\fP ldvr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sgeev (int matrix_layout, char jobvl, char jobvr, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * wr, float * wi, float * vl, \fBlapack_int\fP ldvl, float * vr, \fBlapack_int\fP ldvr)"

.PP
Definition at line 36 of file lapacke_sgeev\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
