.TH "lapacke_stgexc.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_stgexc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_stgexc\fP (int matrix_layout, \fBlapack_logical\fP wantq, \fBlapack_logical\fP wantz, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *b, \fBlapack_int\fP ldb, float *q, \fBlapack_int\fP ldq, float *z, \fBlapack_int\fP ldz, \fBlapack_int\fP *ifst, \fBlapack_int\fP *ilst)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_stgexc (int matrix_layout, \fBlapack_logical\fP wantq, \fBlapack_logical\fP wantz, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * b, \fBlapack_int\fP ldb, float * q, \fBlapack_int\fP ldq, float * z, \fBlapack_int\fP ldz, \fBlapack_int\fP * ifst, \fBlapack_int\fP * ilst)"

.PP
Definition at line 36 of file lapacke_stgexc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
