.TH "lapacke_shsein_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_shsein_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_shsein_work\fP (int matrix_layout, char job, char eigsrc, char initv, \fBlapack_logical\fP *select, \fBlapack_int\fP n, const float *h, \fBlapack_int\fP ldh, float *wr, const float *wi, float *vl, \fBlapack_int\fP ldvl, float *vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP *m, float *work, \fBlapack_int\fP *ifaill, \fBlapack_int\fP *ifailr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_shsein_work (int matrix_layout, char job, char eigsrc, char initv, \fBlapack_logical\fP * select, \fBlapack_int\fP n, const float * h, \fBlapack_int\fP ldh, float * wr, const float * wi, float * vl, \fBlapack_int\fP ldvl, float * vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP * m, float * work, \fBlapack_int\fP * ifaill, \fBlapack_int\fP * ifailr)"

.PP
Definition at line 36 of file lapacke_shsein_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
