.TH "lapacke_zpoequb.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zpoequb.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zpoequb\fP (int matrix_layout, \fBlapack_int\fP n, const \fBlapack_complex_double\fP *a, \fBlapack_int\fP lda, double *s, double *scond, double *amax)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zpoequb (int matrix_layout, \fBlapack_int\fP n, const \fBlapack_complex_double\fP * a, \fBlapack_int\fP lda, double * s, double * scond, double * amax)"

.PP
Definition at line 36 of file lapacke_zpoequb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
