.TH "lapacke_dsyrfsx_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dsyrfsx_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dsyrfsx_work\fP (int matrix_layout, char uplo, char equed, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const double *a, \fBlapack_int\fP lda, const double *af, \fBlapack_int\fP ldaf, const \fBlapack_int\fP *ipiv, const double *s, const double *b, \fBlapack_int\fP ldb, double *x, \fBlapack_int\fP ldx, double *rcond, double *berr, \fBlapack_int\fP n_err_bnds, double *err_bnds_norm, double *err_bnds_comp, \fBlapack_int\fP nparams, double *params, double *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dsyrfsx_work (int matrix_layout, char uplo, char equed, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const double * a, \fBlapack_int\fP lda, const double * af, \fBlapack_int\fP ldaf, const \fBlapack_int\fP * ipiv, const double * s, const double * b, \fBlapack_int\fP ldb, double * x, \fBlapack_int\fP ldx, double * rcond, double * berr, \fBlapack_int\fP n_err_bnds, double * err_bnds_norm, double * err_bnds_comp, \fBlapack_int\fP nparams, double * params, double * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_dsyrfsx_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
