.TH "lapacke_slapy3.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_slapy3.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBLAPACKE_slapy3\fP (float x, float y, float z)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float LAPACKE_slapy3 (float x, float y, float z)"

.PP
Definition at line 36 of file lapacke_slapy3\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
