.TH "lapacke_zgbsv.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zgbsv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zgbsv\fP (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, \fBlapack_complex_double\fP *ab, \fBlapack_int\fP ldab, \fBlapack_int\fP *ipiv, \fBlapack_complex_double\fP *b, \fBlapack_int\fP ldb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zgbsv (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, \fBlapack_complex_double\fP * ab, \fBlapack_int\fP ldab, \fBlapack_int\fP * ipiv, \fBlapack_complex_double\fP * b, \fBlapack_int\fP ldb)"

.PP
Definition at line 36 of file lapacke_zgbsv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
