.TH "lapacke_dorcsd.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dorcsd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dorcsd\fP (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, double *x11, \fBlapack_int\fP ldx11, double *x12, \fBlapack_int\fP ldx12, double *x21, \fBlapack_int\fP ldx21, double *x22, \fBlapack_int\fP ldx22, double *theta, double *u1, \fBlapack_int\fP ldu1, double *u2, \fBlapack_int\fP ldu2, double *v1t, \fBlapack_int\fP ldv1t, double *v2t, \fBlapack_int\fP ldv2t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dorcsd (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, double * x11, \fBlapack_int\fP ldx11, double * x12, \fBlapack_int\fP ldx12, double * x21, \fBlapack_int\fP ldx21, double * x22, \fBlapack_int\fP ldx22, double * theta, double * u1, \fBlapack_int\fP ldu1, double * u2, \fBlapack_int\fP ldu2, double * v1t, \fBlapack_int\fP ldv1t, double * v2t, \fBlapack_int\fP ldv2t)"

.PP
Definition at line 36 of file lapacke_dorcsd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
