.TH "lapacke_sstemr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sstemr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sstemr\fP (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, float *d, float *e, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP *m, float *w, float *z, \fBlapack_int\fP ldz, \fBlapack_int\fP nzc, \fBlapack_int\fP *isuppz, \fBlapack_logical\fP *tryrac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sstemr (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, float * d, float * e, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP * m, float * w, float * z, \fBlapack_int\fP ldz, \fBlapack_int\fP nzc, \fBlapack_int\fP * isuppz, \fBlapack_logical\fP * tryrac)"

.PP
Definition at line 36 of file lapacke_sstemr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
