.TH "lapacke_ctprfs_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_ctprfs_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_ctprfs_work\fP (int matrix_layout, char uplo, char trans, char diag, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP *ap, const \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, const \fBlapack_complex_float\fP *x, \fBlapack_int\fP ldx, float *ferr, float *berr, \fBlapack_complex_float\fP *work, float *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_ctprfs_work (int matrix_layout, char uplo, char trans, char diag, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP * ap, const \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, const \fBlapack_complex_float\fP * x, \fBlapack_int\fP ldx, float * ferr, float * berr, \fBlapack_complex_float\fP * work, float * rwork)"

.PP
Definition at line 36 of file lapacke_ctprfs_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
