.TH "lapacke_sgbrfsx_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sgbrfsx_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sgbrfsx_work\fP (int matrix_layout, char trans, char equed, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, const float *ab, \fBlapack_int\fP ldab, const float *afb, \fBlapack_int\fP ldafb, const \fBlapack_int\fP *ipiv, const float *r, const float *c, const float *b, \fBlapack_int\fP ldb, float *x, \fBlapack_int\fP ldx, float *rcond, float *berr, \fBlapack_int\fP n_err_bnds, float *err_bnds_norm, float *err_bnds_comp, \fBlapack_int\fP nparams, float *params, float *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sgbrfsx_work (int matrix_layout, char trans, char equed, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_int\fP nrhs, const float * ab, \fBlapack_int\fP ldab, const float * afb, \fBlapack_int\fP ldafb, const \fBlapack_int\fP * ipiv, const float * r, const float * c, const float * b, \fBlapack_int\fP ldb, float * x, \fBlapack_int\fP ldx, float * rcond, float * berr, \fBlapack_int\fP n_err_bnds, float * err_bnds_norm, float * err_bnds_comp, \fBlapack_int\fP nparams, float * params, float * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_sgbrfsx_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
