.TH "lapacke_cgges.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgges.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgges\fP (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_C_SELECT2\fP selctg, \fBlapack_int\fP n, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *sdim, \fBlapack_complex_float\fP *alpha, \fBlapack_complex_float\fP *beta, \fBlapack_complex_float\fP *vsl, \fBlapack_int\fP ldvsl, \fBlapack_complex_float\fP *vsr, \fBlapack_int\fP ldvsr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgges (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_C_SELECT2\fP selctg, \fBlapack_int\fP n, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * sdim, \fBlapack_complex_float\fP * alpha, \fBlapack_complex_float\fP * beta, \fBlapack_complex_float\fP * vsl, \fBlapack_int\fP ldvsl, \fBlapack_complex_float\fP * vsr, \fBlapack_int\fP ldvsr)"

.PP
Definition at line 36 of file lapacke_cgges\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
