.TH "lapacke_mangling.h" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_mangling.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLAPACK_GLOBAL\fP(lcname,  UCNAME)   lcname##_"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LAPACK_GLOBAL(lcname, UCNAME)   lcname##_"

.PP
Definition at line 12 of file lapacke_mangling\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
