.TH "lapacke_spp_trans.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_spp_trans.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLAPACKE_spp_trans\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, const float *in, float *out)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LAPACKE_spp_trans (int matrix_layout, char uplo, \fBlapack_int\fP n, const float * in, float * out)"

.PP
Definition at line 40 of file lapacke_spp_trans\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
