.TH "lapacke_cbbcsd.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cbbcsd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cbbcsd\fP (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, float *theta, float *phi, \fBlapack_complex_float\fP *u1, \fBlapack_int\fP ldu1, \fBlapack_complex_float\fP *u2, \fBlapack_int\fP ldu2, \fBlapack_complex_float\fP *v1t, \fBlapack_int\fP ldv1t, \fBlapack_complex_float\fP *v2t, \fBlapack_int\fP ldv2t, float *b11d, float *b11e, float *b12d, float *b12e, float *b21d, float *b21e, float *b22d, float *b22e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cbbcsd (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, float * theta, float * phi, \fBlapack_complex_float\fP * u1, \fBlapack_int\fP ldu1, \fBlapack_complex_float\fP * u2, \fBlapack_int\fP ldu2, \fBlapack_complex_float\fP * v1t, \fBlapack_int\fP ldv1t, \fBlapack_complex_float\fP * v2t, \fBlapack_int\fP ldv2t, float * b11d, float * b11e, float * b12d, float * b12e, float * b21d, float * b21e, float * b22d, float * b22e)"

.PP
Definition at line 36 of file lapacke_cbbcsd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
