.TH "lapacke_zgbbrd_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zgbbrd_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zgbbrd_work\fP (int matrix_layout, char vect, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP ncc, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_complex_double\fP *ab, \fBlapack_int\fP ldab, double *d, double *e, \fBlapack_complex_double\fP *q, \fBlapack_int\fP ldq, \fBlapack_complex_double\fP *pt, \fBlapack_int\fP ldpt, \fBlapack_complex_double\fP *c, \fBlapack_int\fP ldc, \fBlapack_complex_double\fP *work, double *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zgbbrd_work (int matrix_layout, char vect, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP ncc, \fBlapack_int\fP kl, \fBlapack_int\fP ku, \fBlapack_complex_double\fP * ab, \fBlapack_int\fP ldab, double * d, double * e, \fBlapack_complex_double\fP * q, \fBlapack_int\fP ldq, \fBlapack_complex_double\fP * pt, \fBlapack_int\fP ldpt, \fBlapack_complex_double\fP * c, \fBlapack_int\fP ldc, \fBlapack_complex_double\fP * work, double * rwork)"

.PP
Definition at line 36 of file lapacke_zgbbrd_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
