.TH "lapacke_csyconv.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_csyconv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_csyconv\fP (int matrix_layout, char uplo, char way, \fBlapack_int\fP n, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, const \fBlapack_int\fP *ipiv, \fBlapack_complex_float\fP *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_csyconv (int matrix_layout, char uplo, char way, \fBlapack_int\fP n, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, const \fBlapack_int\fP * ipiv, \fBlapack_complex_float\fP * e)"

.PP
Definition at line 36 of file lapacke_csyconv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
