.TH "lapacke_sggbal_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sggbal_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sggbal_work\fP (int matrix_layout, char job, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *ilo, \fBlapack_int\fP *ihi, float *lscale, float *rscale, float *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sggbal_work (int matrix_layout, char job, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * ilo, \fBlapack_int\fP * ihi, float * lscale, float * rscale, float * work)"

.PP
Definition at line 36 of file lapacke_sggbal_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
