.TH "lapacke_sgejsv.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sgejsv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sgejsv\fP (int matrix_layout, char joba, char jobu, char jobv, char jobr, char jobt, char jobp, \fBlapack_int\fP m, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *sva, float *u, \fBlapack_int\fP ldu, float *v, \fBlapack_int\fP ldv, float *stat, \fBlapack_int\fP *istat)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sgejsv (int matrix_layout, char joba, char jobu, char jobv, char jobr, char jobt, char jobp, \fBlapack_int\fP m, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * sva, float * u, \fBlapack_int\fP ldu, float * v, \fBlapack_int\fP ldv, float * stat, \fBlapack_int\fP * istat)"

.PP
Definition at line 36 of file lapacke_sgejsv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
