.TH "lapacke_dtrevc.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dtrevc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dtrevc\fP (int matrix_layout, char side, char howmny, \fBlapack_logical\fP *select, \fBlapack_int\fP n, const double *t, \fBlapack_int\fP ldt, double *vl, \fBlapack_int\fP ldvl, double *vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP *m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dtrevc (int matrix_layout, char side, char howmny, \fBlapack_logical\fP * select, \fBlapack_int\fP n, const double * t, \fBlapack_int\fP ldt, double * vl, \fBlapack_int\fP ldvl, double * vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP * m)"

.PP
Definition at line 36 of file lapacke_dtrevc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
