.TH "lapacke_slassq.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_slassq.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_slassq\fP (\fBlapack_int\fP n, float *x, \fBlapack_int\fP incx, float *scale, float *sumsq)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_slassq (\fBlapack_int\fP n, float * x, \fBlapack_int\fP incx, float * scale, float * sumsq)"

.PP
Definition at line 36 of file lapacke_slassq\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
