.TH "lapacke_stpttf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_stpttf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_stpttf\fP (int matrix_layout, char transr, char uplo, \fBlapack_int\fP n, const float *ap, float *arf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_stpttf (int matrix_layout, char transr, char uplo, \fBlapack_int\fP n, const float * ap, float * arf)"

.PP
Definition at line 36 of file lapacke_stpttf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
