.TH "lapacke_dstemr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dstemr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dstemr\fP (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, double *d, double *e, double vl, double vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP *m, double *w, double *z, \fBlapack_int\fP ldz, \fBlapack_int\fP nzc, \fBlapack_int\fP *isuppz, \fBlapack_logical\fP *tryrac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dstemr (int matrix_layout, char jobz, char range, \fBlapack_int\fP n, double * d, double * e, double vl, double vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP * m, double * w, double * z, \fBlapack_int\fP ldz, \fBlapack_int\fP nzc, \fBlapack_int\fP * isuppz, \fBlapack_logical\fP * tryrac)"

.PP
Definition at line 36 of file lapacke_dstemr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
