.TH "lapacke_cgesvdx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgesvdx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgesvdx\fP (int matrix_layout, char jobu, char jobvt, char range, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP *ns, float *s, \fBlapack_complex_float\fP *u, \fBlapack_int\fP ldu, \fBlapack_complex_float\fP *vt, \fBlapack_int\fP ldvt, \fBlapack_int\fP *superb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgesvdx (int matrix_layout, char jobu, char jobvt, char range, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, float vl, float vu, \fBlapack_int\fP il, \fBlapack_int\fP iu, \fBlapack_int\fP * ns, float * s, \fBlapack_complex_float\fP * u, \fBlapack_int\fP ldu, \fBlapack_complex_float\fP * vt, \fBlapack_int\fP ldvt, \fBlapack_int\fP * superb)"

.PP
Definition at line 36 of file lapacke_cgesvdx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
