.TH "lapacke_spstrf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_spstrf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_spstrf\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, \fBlapack_int\fP *piv, \fBlapack_int\fP *rank, float tol)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_spstrf (int matrix_layout, char uplo, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, \fBlapack_int\fP * piv, \fBlapack_int\fP * rank, float tol)"

.PP
Definition at line 36 of file lapacke_spstrf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
