.TH "lapacke_sposvx_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sposvx_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sposvx_work\fP (int matrix_layout, char fact, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, float *a, \fBlapack_int\fP lda, float *af, \fBlapack_int\fP ldaf, char *equed, float *s, float *b, \fBlapack_int\fP ldb, float *x, \fBlapack_int\fP ldx, float *rcond, float *ferr, float *berr, float *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sposvx_work (int matrix_layout, char fact, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, float * a, \fBlapack_int\fP lda, float * af, \fBlapack_int\fP ldaf, char * equed, float * s, float * b, \fBlapack_int\fP ldb, float * x, \fBlapack_int\fP ldx, float * rcond, float * ferr, float * berr, float * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_sposvx_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
