.TH "lapacke_example_aux.h" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_example_aux.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_matrix_rowmajor\fP (char *desc, \fBlapack_int\fP m, \fBlapack_int\fP n, double *mat, \fBlapack_int\fP ldm)"
.br
.ti -1c
.RI "void \fBprint_matrix_colmajor\fP (char *desc, \fBlapack_int\fP m, \fBlapack_int\fP n, double *mat, \fBlapack_int\fP ldm)"
.br
.ti -1c
.RI "void \fBprint_vector\fP (char *desc, \fBlapack_int\fP n, \fBlapack_int\fP *vec)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_matrix_colmajor (char * desc, \fBlapack_int\fP m, \fBlapack_int\fP n, double * mat, \fBlapack_int\fP ldm)"

.PP
Definition at line 17 of file lapacke_example_aux\&.c\&.
.SS "void print_matrix_rowmajor (char * desc, \fBlapack_int\fP m, \fBlapack_int\fP n, double * mat, \fBlapack_int\fP ldm)"

.PP
Definition at line 5 of file lapacke_example_aux\&.c\&.
.SS "void print_vector (char * desc, \fBlapack_int\fP n, \fBlapack_int\fP * vec)"

.PP
Definition at line 28 of file lapacke_example_aux\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
