.TH "lapacke_dbdsdc_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dbdsdc_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dbdsdc_work\fP (int matrix_layout, char uplo, char compq, \fBlapack_int\fP n, double *d, double *e, double *u, \fBlapack_int\fP ldu, double *vt, \fBlapack_int\fP ldvt, double *q, \fBlapack_int\fP *iq, double *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dbdsdc_work (int matrix_layout, char uplo, char compq, \fBlapack_int\fP n, double * d, double * e, double * u, \fBlapack_int\fP ldu, double * vt, \fBlapack_int\fP ldvt, double * q, \fBlapack_int\fP * iq, double * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_dbdsdc_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
