.TH "lapacke_chpsvx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_chpsvx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_chpsvx\fP (int matrix_layout, char fact, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP *ap, \fBlapack_complex_float\fP *afp, \fBlapack_int\fP *ipiv, const \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP *x, \fBlapack_int\fP ldx, float *rcond, float *ferr, float *berr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_chpsvx (int matrix_layout, char fact, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const \fBlapack_complex_float\fP * ap, \fBlapack_complex_float\fP * afp, \fBlapack_int\fP * ipiv, const \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP * x, \fBlapack_int\fP ldx, float * rcond, float * ferr, float * berr)"

.PP
Definition at line 36 of file lapacke_chpsvx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
