.TH "lapacke_slarft.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_slarft.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_slarft\fP (int matrix_layout, char direct, char storev, \fBlapack_int\fP n, \fBlapack_int\fP k, const float *v, \fBlapack_int\fP ldv, const float *tau, float *t, \fBlapack_int\fP ldt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_slarft (int matrix_layout, char direct, char storev, \fBlapack_int\fP n, \fBlapack_int\fP k, const float * v, \fBlapack_int\fP ldv, const float * tau, float * t, \fBlapack_int\fP ldt)"

.PP
Definition at line 36 of file lapacke_slarft\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
