.TH "lapacke_sbdsdc.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sbdsdc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sbdsdc\fP (int matrix_layout, char uplo, char compq, \fBlapack_int\fP n, float *d, float *e, float *u, \fBlapack_int\fP ldu, float *vt, \fBlapack_int\fP ldvt, float *q, \fBlapack_int\fP *iq)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sbdsdc (int matrix_layout, char uplo, char compq, \fBlapack_int\fP n, float * d, float * e, float * u, \fBlapack_int\fP ldu, float * vt, \fBlapack_int\fP ldvt, float * q, \fBlapack_int\fP * iq)"

.PP
Definition at line 36 of file lapacke_sbdsdc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
