.TH "lapacke_sspgvd.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sspgvd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sspgvd\fP (int matrix_layout, \fBlapack_int\fP itype, char jobz, char uplo, \fBlapack_int\fP n, float *ap, float *bp, float *w, float *z, \fBlapack_int\fP ldz)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sspgvd (int matrix_layout, \fBlapack_int\fP itype, char jobz, char uplo, \fBlapack_int\fP n, float * ap, float * bp, float * w, float * z, \fBlapack_int\fP ldz)"

.PP
Definition at line 36 of file lapacke_sspgvd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
