.TH "lapacke_chetri2.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_chetri2.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_chetri2\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, const \fBlapack_int\fP *ipiv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_chetri2 (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, const \fBlapack_int\fP * ipiv)"

.PP
Definition at line 36 of file lapacke_chetri2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
