.TH "lapacke_dsbgst.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dsbgst.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dsbgst\fP (int matrix_layout, char vect, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ka, \fBlapack_int\fP kb, double *ab, \fBlapack_int\fP ldab, const double *bb, \fBlapack_int\fP ldbb, double *x, \fBlapack_int\fP ldx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dsbgst (int matrix_layout, char vect, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ka, \fBlapack_int\fP kb, double * ab, \fBlapack_int\fP ldab, const double * bb, \fBlapack_int\fP ldbb, double * x, \fBlapack_int\fP ldx)"

.PP
Definition at line 36 of file lapacke_dsbgst\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
