.TH "lapacke_cgttrf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgttrf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgttrf\fP (\fBlapack_int\fP n, \fBlapack_complex_float\fP *dl, \fBlapack_complex_float\fP *d, \fBlapack_complex_float\fP *du, \fBlapack_complex_float\fP *du2, \fBlapack_int\fP *ipiv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgttrf (\fBlapack_int\fP n, \fBlapack_complex_float\fP * dl, \fBlapack_complex_float\fP * d, \fBlapack_complex_float\fP * du, \fBlapack_complex_float\fP * du2, \fBlapack_int\fP * ipiv)"

.PP
Definition at line 36 of file lapacke_cgttrf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
