.TH "lapacke_dtfsm.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dtfsm.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dtfsm\fP (int matrix_layout, char transr, char side, char uplo, char trans, char diag, \fBlapack_int\fP m, \fBlapack_int\fP n, double alpha, const double *a, double *b, \fBlapack_int\fP ldb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dtfsm (int matrix_layout, char transr, char side, char uplo, char trans, char diag, \fBlapack_int\fP m, \fBlapack_int\fP n, double alpha, const double * a, double * b, \fBlapack_int\fP ldb)"

.PP
Definition at line 36 of file lapacke_dtfsm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
