.TH "lapacke_strsna.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_strsna.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_strsna\fP (int matrix_layout, char job, char howmny, const \fBlapack_logical\fP *select, \fBlapack_int\fP n, const float *t, \fBlapack_int\fP ldt, const float *vl, \fBlapack_int\fP ldvl, const float *vr, \fBlapack_int\fP ldvr, float *s, float *sep, \fBlapack_int\fP mm, \fBlapack_int\fP *m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_strsna (int matrix_layout, char job, char howmny, const \fBlapack_logical\fP * select, \fBlapack_int\fP n, const float * t, \fBlapack_int\fP ldt, const float * vl, \fBlapack_int\fP ldvl, const float * vr, \fBlapack_int\fP ldvr, float * s, float * sep, \fBlapack_int\fP mm, \fBlapack_int\fP * m)"

.PP
Definition at line 36 of file lapacke_strsna\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
