.TH "lapacke_cstein_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cstein_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cstein_work\fP (int matrix_layout, \fBlapack_int\fP n, const float *d, const float *e, \fBlapack_int\fP m, const float *w, const \fBlapack_int\fP *iblock, const \fBlapack_int\fP *isplit, \fBlapack_complex_float\fP *z, \fBlapack_int\fP ldz, float *work, \fBlapack_int\fP *iwork, \fBlapack_int\fP *ifailv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cstein_work (int matrix_layout, \fBlapack_int\fP n, const float * d, const float * e, \fBlapack_int\fP m, const float * w, const \fBlapack_int\fP * iblock, const \fBlapack_int\fP * isplit, \fBlapack_complex_float\fP * z, \fBlapack_int\fP ldz, float * work, \fBlapack_int\fP * iwork, \fBlapack_int\fP * ifailv)"

.PP
Definition at line 36 of file lapacke_cstein_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
