.TH "lapacke_sgges3_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sgges3_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sgges3_work\fP (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_S_SELECT3\fP selctg, \fBlapack_int\fP n, float *a, \fBlapack_int\fP lda, float *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *sdim, float *alphar, float *alphai, float *beta, float *vsl, \fBlapack_int\fP ldvsl, float *vsr, \fBlapack_int\fP ldvsr, float *work, \fBlapack_int\fP lwork, \fBlapack_logical\fP *bwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sgges3_work (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_S_SELECT3\fP selctg, \fBlapack_int\fP n, float * a, \fBlapack_int\fP lda, float * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * sdim, float * alphar, float * alphai, float * beta, float * vsl, \fBlapack_int\fP ldvsl, float * vsr, \fBlapack_int\fP ldvsr, float * work, \fBlapack_int\fP lwork, \fBlapack_logical\fP * bwork)"

.PP
Definition at line 36 of file lapacke_sgges3_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
