.TH "lapacke_dpbrfs.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dpbrfs.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dpbrfs\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_int\fP nrhs, const double *ab, \fBlapack_int\fP ldab, const double *afb, \fBlapack_int\fP ldafb, const double *b, \fBlapack_int\fP ldb, double *x, \fBlapack_int\fP ldx, double *ferr, double *berr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dpbrfs (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_int\fP nrhs, const double * ab, \fBlapack_int\fP ldab, const double * afb, \fBlapack_int\fP ldafb, const double * b, \fBlapack_int\fP ldb, double * x, \fBlapack_int\fP ldx, double * ferr, double * berr)"

.PP
Definition at line 36 of file lapacke_dpbrfs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
