.TH "lapacke_nancheck.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_nancheck.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLAPACKE_set_nancheck\fP (int flag)"
.br
.ti -1c
.RI "int \fBLAPACKE_get_nancheck\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int LAPACKE_get_nancheck ()"

.PP
Definition at line 43 of file lapacke_nancheck\&.c\&.
.SS "void LAPACKE_set_nancheck (int flag)"

.PP
Definition at line 38 of file lapacke_nancheck\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
