.TH "lapacke_clarfg.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_clarfg.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_clarfg\fP (\fBlapack_int\fP n, \fBlapack_complex_float\fP *alpha, \fBlapack_complex_float\fP *x, \fBlapack_int\fP incx, \fBlapack_complex_float\fP *tau)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_clarfg (\fBlapack_int\fP n, \fBlapack_complex_float\fP * alpha, \fBlapack_complex_float\fP * x, \fBlapack_int\fP incx, \fBlapack_complex_float\fP * tau)"

.PP
Definition at line 36 of file lapacke_clarfg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
