.TH "lapacke_sopgtr_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sopgtr_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sopgtr_work\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, const float *ap, const float *tau, float *q, \fBlapack_int\fP ldq, float *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sopgtr_work (int matrix_layout, char uplo, \fBlapack_int\fP n, const float * ap, const float * tau, float * q, \fBlapack_int\fP ldq, float * work)"

.PP
Definition at line 36 of file lapacke_sopgtr_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
