.TH "lapacke_dpf_nancheck.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dpf_nancheck.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_logical\fP \fBLAPACKE_dpf_nancheck\fP (\fBlapack_int\fP n, const double *a)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_logical\fP LAPACKE_dpf_nancheck (\fBlapack_int\fP n, const double * a)"

.PP
Definition at line 41 of file lapacke_dpf_nancheck\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
