.TH "lapacke_zpttrf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zpttrf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zpttrf\fP (\fBlapack_int\fP n, double *d, \fBlapack_complex_double\fP *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zpttrf (\fBlapack_int\fP n, double * d, \fBlapack_complex_double\fP * e)"

.PP
Definition at line 36 of file lapacke_zpttrf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
