.TH "lapacke_dggevx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dggevx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dggevx\fP (int matrix_layout, char balanc, char jobvl, char jobvr, char sense, \fBlapack_int\fP n, double *a, \fBlapack_int\fP lda, double *b, \fBlapack_int\fP ldb, double *alphar, double *alphai, double *beta, double *vl, \fBlapack_int\fP ldvl, double *vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP *ilo, \fBlapack_int\fP *ihi, double *lscale, double *rscale, double *abnrm, double *bbnrm, double *rconde, double *rcondv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dggevx (int matrix_layout, char balanc, char jobvl, char jobvr, char sense, \fBlapack_int\fP n, double * a, \fBlapack_int\fP lda, double * b, \fBlapack_int\fP ldb, double * alphar, double * alphai, double * beta, double * vl, \fBlapack_int\fP ldvl, double * vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP * ilo, \fBlapack_int\fP * ihi, double * lscale, double * rscale, double * abnrm, double * bbnrm, double * rconde, double * rcondv)"

.PP
Definition at line 36 of file lapacke_dggevx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
