.TH "lapacke_ztgevc.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_ztgevc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_ztgevc\fP (int matrix_layout, char side, char howmny, const \fBlapack_logical\fP *select, \fBlapack_int\fP n, const \fBlapack_complex_double\fP *s, \fBlapack_int\fP lds, const \fBlapack_complex_double\fP *p, \fBlapack_int\fP ldp, \fBlapack_complex_double\fP *vl, \fBlapack_int\fP ldvl, \fBlapack_complex_double\fP *vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP *m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_ztgevc (int matrix_layout, char side, char howmny, const \fBlapack_logical\fP * select, \fBlapack_int\fP n, const \fBlapack_complex_double\fP * s, \fBlapack_int\fP lds, const \fBlapack_complex_double\fP * p, \fBlapack_int\fP ldp, \fBlapack_complex_double\fP * vl, \fBlapack_int\fP ldvl, \fBlapack_complex_double\fP * vr, \fBlapack_int\fP ldvr, \fBlapack_int\fP mm, \fBlapack_int\fP * m)"

.PP
Definition at line 36 of file lapacke_ztgevc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
