.TH "lapacke_cgelsy_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgelsy_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgelsy_work\fP (int matrix_layout, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *jpvt, float rcond, \fBlapack_int\fP *rank, \fBlapack_complex_float\fP *work, \fBlapack_int\fP lwork, float *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgelsy_work (int matrix_layout, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * jpvt, float rcond, \fBlapack_int\fP * rank, \fBlapack_complex_float\fP * work, \fBlapack_int\fP lwork, float * rwork)"

.PP
Definition at line 36 of file lapacke_cgelsy_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
