.TH "lapacke_cggsvd.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cggsvd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cggsvd\fP (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP p, \fBlapack_int\fP *k, \fBlapack_int\fP *l, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, float *alpha, float *beta, \fBlapack_complex_float\fP *u, \fBlapack_int\fP ldu, \fBlapack_complex_float\fP *v, \fBlapack_int\fP ldv, \fBlapack_complex_float\fP *q, \fBlapack_int\fP ldq, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cggsvd (int matrix_layout, char jobu, char jobv, char jobq, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP p, \fBlapack_int\fP * k, \fBlapack_int\fP * l, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, float * alpha, float * beta, \fBlapack_complex_float\fP * u, \fBlapack_int\fP ldu, \fBlapack_complex_float\fP * v, \fBlapack_int\fP ldv, \fBlapack_complex_float\fP * q, \fBlapack_int\fP ldq, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_cggsvd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
