.TH "lapacke_dgbcon.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dgbcon.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dgbcon\fP (int matrix_layout, char norm, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, const double *ab, \fBlapack_int\fP ldab, const \fBlapack_int\fP *ipiv, double anorm, double *rcond)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dgbcon (int matrix_layout, char norm, \fBlapack_int\fP n, \fBlapack_int\fP kl, \fBlapack_int\fP ku, const double * ab, \fBlapack_int\fP ldab, const \fBlapack_int\fP * ipiv, double anorm, double * rcond)"

.PP
Definition at line 36 of file lapacke_dgbcon\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
