.TH "lapacke_zsy_trans.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zsy_trans.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLAPACKE_zsy_trans\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, const \fBlapack_complex_double\fP *in, \fBlapack_int\fP ldin, \fBlapack_complex_double\fP *out, \fBlapack_int\fP ldout)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LAPACKE_zsy_trans (int matrix_layout, char uplo, \fBlapack_int\fP n, const \fBlapack_complex_double\fP * in, \fBlapack_int\fP ldin, \fBlapack_complex_double\fP * out, \fBlapack_int\fP ldout)"

.PP
Definition at line 40 of file lapacke_zsy_trans\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
