.TH "lapacke_cunmqr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cunmqr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cunmqr\fP (int matrix_layout, char side, char trans, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, const \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP *tau, \fBlapack_complex_float\fP *c, \fBlapack_int\fP ldc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cunmqr (int matrix_layout, char side, char trans, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, const \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP * tau, \fBlapack_complex_float\fP * c, \fBlapack_int\fP ldc)"

.PP
Definition at line 36 of file lapacke_cunmqr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
