.TH "lapacke_cgtsv.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cgtsv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cgtsv\fP (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, \fBlapack_complex_float\fP *dl, \fBlapack_complex_float\fP *d, \fBlapack_complex_float\fP *du, \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cgtsv (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, \fBlapack_complex_float\fP * dl, \fBlapack_complex_float\fP * d, \fBlapack_complex_float\fP * du, \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb)"

.PP
Definition at line 36 of file lapacke_cgtsv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
