.TH "lapacke_dggesx.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dggesx.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dggesx\fP (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_D_SELECT3\fP selctg, char sense, \fBlapack_int\fP n, double *a, \fBlapack_int\fP lda, double *b, \fBlapack_int\fP ldb, \fBlapack_int\fP *sdim, double *alphar, double *alphai, double *beta, double *vsl, \fBlapack_int\fP ldvsl, double *vsr, \fBlapack_int\fP ldvsr, double *rconde, double *rcondv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dggesx (int matrix_layout, char jobvsl, char jobvsr, char sort, \fBLAPACK_D_SELECT3\fP selctg, char sense, \fBlapack_int\fP n, double * a, \fBlapack_int\fP lda, double * b, \fBlapack_int\fP ldb, \fBlapack_int\fP * sdim, double * alphar, double * alphai, double * beta, double * vsl, \fBlapack_int\fP ldvsl, double * vsr, \fBlapack_int\fP ldvsr, double * rconde, double * rcondv)"

.PP
Definition at line 36 of file lapacke_dggesx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
