.TH "lapacke_stprfs_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_stprfs_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_stprfs_work\fP (int matrix_layout, char uplo, char trans, char diag, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float *ap, const float *b, \fBlapack_int\fP ldb, const float *x, \fBlapack_int\fP ldx, float *ferr, float *berr, float *work, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_stprfs_work (int matrix_layout, char uplo, char trans, char diag, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float * ap, const float * b, \fBlapack_int\fP ldb, const float * x, \fBlapack_int\fP ldx, float * ferr, float * berr, float * work, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_stprfs_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
