.TH "lapacke_make_complex_double.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_make_complex_double.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke\&.h'\fP
.br
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_complex_double\fP \fBlapack_make_complex_double\fP (double re, double im)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_complex_double\fP lapack_make_complex_double (double re, double im)"

.PP
Definition at line 37 of file lapacke_make_complex_double\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
