.TH "lapacke_zhseqr_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zhseqr_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zhseqr_work\fP (int matrix_layout, char job, char compz, \fBlapack_int\fP n, \fBlapack_int\fP ilo, \fBlapack_int\fP ihi, \fBlapack_complex_double\fP *h, \fBlapack_int\fP ldh, \fBlapack_complex_double\fP *w, \fBlapack_complex_double\fP *z, \fBlapack_int\fP ldz, \fBlapack_complex_double\fP *work, \fBlapack_int\fP lwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zhseqr_work (int matrix_layout, char job, char compz, \fBlapack_int\fP n, \fBlapack_int\fP ilo, \fBlapack_int\fP ihi, \fBlapack_complex_double\fP * h, \fBlapack_int\fP ldh, \fBlapack_complex_double\fP * w, \fBlapack_complex_double\fP * z, \fBlapack_int\fP ldz, \fBlapack_complex_double\fP * work, \fBlapack_int\fP lwork)"

.PP
Definition at line 36 of file lapacke_zhseqr_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
