.TH "lapacke_zhbevd.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zhbevd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zhbevd\fP (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_complex_double\fP *ab, \fBlapack_int\fP ldab, double *w, \fBlapack_complex_double\fP *z, \fBlapack_int\fP ldz)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zhbevd (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_complex_double\fP * ab, \fBlapack_int\fP ldab, double * w, \fBlapack_complex_double\fP * z, \fBlapack_int\fP ldz)"

.PP
Definition at line 36 of file lapacke_zhbevd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
