.TH "lapacke_zuncsd_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zuncsd_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zuncsd_work\fP (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, \fBlapack_complex_double\fP *x11, \fBlapack_int\fP ldx11, \fBlapack_complex_double\fP *x12, \fBlapack_int\fP ldx12, \fBlapack_complex_double\fP *x21, \fBlapack_int\fP ldx21, \fBlapack_complex_double\fP *x22, \fBlapack_int\fP ldx22, double *theta, \fBlapack_complex_double\fP *u1, \fBlapack_int\fP ldu1, \fBlapack_complex_double\fP *u2, \fBlapack_int\fP ldu2, \fBlapack_complex_double\fP *v1t, \fBlapack_int\fP ldv1t, \fBlapack_complex_double\fP *v2t, \fBlapack_int\fP ldv2t, \fBlapack_complex_double\fP *work, \fBlapack_int\fP lwork, double *rwork, \fBlapack_int\fP lrwork, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zuncsd_work (int matrix_layout, char jobu1, char jobu2, char jobv1t, char jobv2t, char trans, char signs, \fBlapack_int\fP m, \fBlapack_int\fP p, \fBlapack_int\fP q, \fBlapack_complex_double\fP * x11, \fBlapack_int\fP ldx11, \fBlapack_complex_double\fP * x12, \fBlapack_int\fP ldx12, \fBlapack_complex_double\fP * x21, \fBlapack_int\fP ldx21, \fBlapack_complex_double\fP * x22, \fBlapack_int\fP ldx22, double * theta, \fBlapack_complex_double\fP * u1, \fBlapack_int\fP ldu1, \fBlapack_complex_double\fP * u2, \fBlapack_int\fP ldu2, \fBlapack_complex_double\fP * v1t, \fBlapack_int\fP ldv1t, \fBlapack_complex_double\fP * v2t, \fBlapack_int\fP ldv2t, \fBlapack_complex_double\fP * work, \fBlapack_int\fP lwork, double * rwork, \fBlapack_int\fP lrwork, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_zuncsd_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
