.TH "lapacke_chbtrd_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_chbtrd_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_chbtrd_work\fP (int matrix_layout, char vect, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_complex_float\fP *ab, \fBlapack_int\fP ldab, float *d, float *e, \fBlapack_complex_float\fP *q, \fBlapack_int\fP ldq, \fBlapack_complex_float\fP *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_chbtrd_work (int matrix_layout, char vect, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, \fBlapack_complex_float\fP * ab, \fBlapack_int\fP ldab, float * d, float * e, \fBlapack_complex_float\fP * q, \fBlapack_int\fP ldq, \fBlapack_complex_float\fP * work)"

.PP
Definition at line 36 of file lapacke_chbtrd_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
