.TH "lapacke_dpbcon.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dpbcon.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dpbcon\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, const double *ab, \fBlapack_int\fP ldab, double anorm, double *rcond)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dpbcon (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP kd, const double * ab, \fBlapack_int\fP ldab, double anorm, double * rcond)"

.PP
Definition at line 36 of file lapacke_dpbcon\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
