.TH "lapacke_xerbla.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_xerbla.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLAPACKE_xerbla\fP (const char *name, \fBlapack_int\fP info)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LAPACKE_xerbla (const char * name, \fBlapack_int\fP info)"

.PP
Definition at line 37 of file lapacke_xerbla\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
