.TH "lapacke_dggqrf.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dggqrf.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_dggqrf\fP (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP m, \fBlapack_int\fP p, double *a, \fBlapack_int\fP lda, double *taua, double *b, \fBlapack_int\fP ldb, double *taub)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_dggqrf (int matrix_layout, \fBlapack_int\fP n, \fBlapack_int\fP m, \fBlapack_int\fP p, double * a, \fBlapack_int\fP lda, double * taua, double * b, \fBlapack_int\fP ldb, double * taub)"

.PP
Definition at line 36 of file lapacke_dggqrf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
