.TH "lapacke_clarnv.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_clarnv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_clarnv\fP (\fBlapack_int\fP idist, \fBlapack_int\fP *iseed, \fBlapack_int\fP n, \fBlapack_complex_float\fP *x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_clarnv (\fBlapack_int\fP idist, \fBlapack_int\fP * iseed, \fBlapack_int\fP n, \fBlapack_complex_float\fP * x)"

.PP
Definition at line 36 of file lapacke_clarnv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
