.TH "lapacke_cungqr.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cungqr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cungqr\fP (int matrix_layout, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP *tau)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cungqr (int matrix_layout, \fBlapack_int\fP m, \fBlapack_int\fP n, \fBlapack_int\fP k, \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP * tau)"

.PP
Definition at line 36 of file lapacke_cungqr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
