.TH "lapacke_zhbgv_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_zhbgv_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_zhbgv_work\fP (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ka, \fBlapack_int\fP kb, \fBlapack_complex_double\fP *ab, \fBlapack_int\fP ldab, \fBlapack_complex_double\fP *bb, \fBlapack_int\fP ldbb, double *w, \fBlapack_complex_double\fP *z, \fBlapack_int\fP ldz, \fBlapack_complex_double\fP *work, double *rwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_zhbgv_work (int matrix_layout, char jobz, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP ka, \fBlapack_int\fP kb, \fBlapack_complex_double\fP * ab, \fBlapack_int\fP ldab, \fBlapack_complex_double\fP * bb, \fBlapack_int\fP ldbb, double * w, \fBlapack_complex_double\fP * z, \fBlapack_int\fP ldz, \fBlapack_complex_double\fP * work, double * rwork)"

.PP
Definition at line 36 of file lapacke_zhbgv_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
