.TH "lapacke_ctgsna_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_ctgsna_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_ctgsna_work\fP (int matrix_layout, char job, char howmny, const \fBlapack_logical\fP *select, \fBlapack_int\fP n, const \fBlapack_complex_float\fP *a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, const \fBlapack_complex_float\fP *vl, \fBlapack_int\fP ldvl, const \fBlapack_complex_float\fP *vr, \fBlapack_int\fP ldvr, float *s, float *dif, \fBlapack_int\fP mm, \fBlapack_int\fP *m, \fBlapack_complex_float\fP *work, \fBlapack_int\fP lwork, \fBlapack_int\fP *iwork)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_ctgsna_work (int matrix_layout, char job, char howmny, const \fBlapack_logical\fP * select, \fBlapack_int\fP n, const \fBlapack_complex_float\fP * a, \fBlapack_int\fP lda, const \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, const \fBlapack_complex_float\fP * vl, \fBlapack_int\fP ldvl, const \fBlapack_complex_float\fP * vr, \fBlapack_int\fP ldvr, float * s, float * dif, \fBlapack_int\fP mm, \fBlapack_int\fP * m, \fBlapack_complex_float\fP * work, \fBlapack_int\fP lwork, \fBlapack_int\fP * iwork)"

.PP
Definition at line 36 of file lapacke_ctgsna_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
