.TH "lapacke_sptsvx_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_sptsvx_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_sptsvx_work\fP (int matrix_layout, char fact, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float *d, const float *e, float *df, float *ef, const float *b, \fBlapack_int\fP ldb, float *x, \fBlapack_int\fP ldx, float *rcond, float *ferr, float *berr, float *work)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_sptsvx_work (int matrix_layout, char fact, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float * d, const float * e, float * df, float * ef, const float * b, \fBlapack_int\fP ldb, float * x, \fBlapack_int\fP ldx, float * rcond, float * ferr, float * berr, float * work)"

.PP
Definition at line 36 of file lapacke_sptsvx_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
