.TH "lapacke_cptrfs.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_cptrfs.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlapack_int\fP \fBLAPACKE_cptrfs\fP (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float *d, const \fBlapack_complex_float\fP *e, const float *df, const \fBlapack_complex_float\fP *ef, const \fBlapack_complex_float\fP *b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP *x, \fBlapack_int\fP ldx, float *ferr, float *berr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBlapack_int\fP LAPACKE_cptrfs (int matrix_layout, char uplo, \fBlapack_int\fP n, \fBlapack_int\fP nrhs, const float * d, const \fBlapack_complex_float\fP * e, const float * df, const \fBlapack_complex_float\fP * ef, const \fBlapack_complex_float\fP * b, \fBlapack_int\fP ldb, \fBlapack_complex_float\fP * x, \fBlapack_int\fP ldx, float * ferr, float * berr)"

.PP
Definition at line 36 of file lapacke_cptrfs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
