.TH "lapacke_dlapy2_work.c" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lapacke_dlapy2_work.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lapacke_utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBLAPACKE_dlapy2_work\fP (double x, double y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double LAPACKE_dlapy2_work (double x, double y)"

.PP
Definition at line 36 of file lapacke_dlapy2_work\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
