.TH "scabs1.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scabs1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real function \fBscabs1\fP (Z)"
.br
.RI "\fBSCABS1\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "real function scabs1 (complex Z)"

.PP
\fBSCABS1\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SCABS1 computes |Re(.)| + |Im(.)| of a complex number
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIZ\fP 
.PP
.nf
          Z is COMPLEX
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2017 
.RE
.PP

.PP
Definition at line 48 of file scabs1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
