.TH "slarfy.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slarfy.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslarfy\fP (UPLO, \fBN\fP, V, INCV, TAU, C, LDC, WORK)"
.br
.RI "\fBSLARFY\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slarfy (character UPLO, integer N, real, dimension( * ) V, integer INCV, real TAU, real, dimension( ldc, * ) C, integer LDC, real, dimension( * ) WORK)"

.PP
\fBSLARFY\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLARFY applies an elementary reflector, or Householder matrix, H,
 to an n x n symmetric matrix C, from both the left and the right.

 H is represented in the form

    H = I - tau * v * v'

 where  tau  is a scalar and  v  is a vector.

 If  tau  is  zero, then  H  is taken to be the unit matrix.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIUPLO\fP 
.PP
.nf
          UPLO is CHARACTER*1
          Specifies whether the upper or lower triangular part of the
          symmetric matrix C is stored.
          = 'U':  Upper triangle
          = 'L':  Lower triangle
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of rows and columns of the matrix C.  N >= 0.
.fi
.PP
.br
\fIV\fP 
.PP
.nf
          V is REAL array, dimension
                  (1 + (N-1)*abs(INCV))
          The vector v as described above.
.fi
.PP
.br
\fIINCV\fP 
.PP
.nf
          INCV is INTEGER
          The increment between successive elements of v.  INCV must
          not be zero.
.fi
.PP
.br
\fITAU\fP 
.PP
.nf
          TAU is REAL
          The value tau as described above.
.fi
.PP
.br
\fIC\fP 
.PP
.nf
          C is REAL array, dimension (LDC, N)
          On entry, the matrix C.
          On exit, C is overwritten by H * C * H'.
.fi
.PP
.br
\fILDC\fP 
.PP
.nf
          LDC is INTEGER
          The leading dimension of the array C.  LDC >= max( 1, N ).
.fi
.PP
.br
\fIWORK\fP 
.PP
.nf
          WORK is REAL array, dimension (N)
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
December 2016 
.RE
.PP

.PP
Definition at line 110 of file slarfy\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
