.TH "srot.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srot.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsrot\fP (\fBN\fP, SX, INCX, SY, INCY, C, S)"
.br
.RI "\fBSROT\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine srot (integer N, real, dimension(*) SX, integer INCX, real, dimension(*) SY, integer INCY, real C, real S)"

.PP
\fBSROT\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
    applies a plane rotation.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
         number of elements in input vector(s)
.fi
.PP
.br
\fISX\fP 
.PP
.nf
          SX is REAL array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
         storage spacing between elements of SX
.fi
.PP
.br
\fISY\fP 
.PP
.nf
          SY is REAL array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
         storage spacing between elements of SY
.fi
.PP
.br
\fIC\fP 
.PP
.nf
          C is REAL
.fi
.PP
.br
\fIS\fP 
.PP
.nf
          S is REAL
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2017 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, linpack, 3/11/78.
     modified 12/3/93, array(1) declarations changed to array(*)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 94 of file srot\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
