.TH "srotg.f" 3 "Tue Nov 14 2017" "Version 3.8.0" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srotg.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsrotg\fP (SA, SB, C, S)"
.br
.RI "\fBSROTG\fP "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine srotg (real SA, real SB, real C, real S)"

.PP
\fBSROTG\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
    SROTG construct givens plane rotation.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISA\fP 
.PP
.nf
          SA is REAL
.fi
.PP
.br
\fISB\fP 
.PP
.nf
          SB is REAL
.fi
.PP
.br
\fIC\fP 
.PP
.nf
          C is REAL
.fi
.PP
.br
\fIS\fP 
.PP
.nf
          S is REAL
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2017 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, linpack, 3/11/78.
.fi
.PP
 
.RE
.PP

.PP
Definition at line 71 of file srotg\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
